version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:


services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    labels:
      ch.medgate.monitoring: "true"
    depends_on:
      - cadvisor
      - alertmanager
    networks:
      - back-tier
    deploy:
      placement:
        constraints:
          - node.hostname == ${MONITORING_HOST_NAME}
  node-exporter:
    image: prom/node-exporter
    labels:
      ch.medgate.monitoring: "true"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    networks:
      - back-tier
    deploy:
  alertmanager:
    image: prom/alertmanager
    labels:
      ch.medgate.monitoring: "true"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    deploy:
      placement:
        constraints:
          - node.hostname == ${MONITORING_HOST_NAME}
  cadvisor:
    image: google/cadvisor
    labels:
      ch.medgate.monitoring: "true"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - back-tier
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    labels:
      ch.medgate.monitoring: "true"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier